Write-Host "Tatnez beginner workflow"
Write-Host ""
Write-Host "Run these commands in order:"
Write-Host "1. .\scripts\install-prerequisites.ps1"
Write-Host "2. Close this shell"
Write-Host "3. Reopen a Developer PowerShell for Visual Studio"
Write-Host "4. .\scripts\check-prerequisites.ps1"
Write-Host "5. .\scripts\build.ps1"
Write-Host "6. .\scripts\run.ps1"
Write-Host "7. .\scripts\test.ps1"
Write-Host ""
Write-Host "Optional documentation commands:"
Write-Host ".\scripts\install-prerequisites.ps1 -IncludeDocumentationTools -IncludeWikiTools"
Write-Host ".\scripts\build-docs.ps1"
Write-Host ".\scripts\serve-docs.ps1"
Write-Host ".\scripts\start-wiki.ps1"
Write-Host ""
Write-Host "Safe first run:"
Write-Host ".\scripts\run.ps1"
Write-Host ""
Write-Host "First live hardware run:"
Write-Host ".\scripts\run.ps1 -LiveHardware -ControllerIndex 0"
